CREATE TABLE Rol (
id INT AUTO_INCREMENT NOT NULL, 
descripcion VARCHAR(64) NOT NULL, 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


CREATE TABLE Usuario (
id INT AUTO_INCREMENT NOT NULL, 
nombre VARCHAR(64) NOT NULL, 
apellido VARCHAR(64) NOT NULL, 
telefono VARCHAR(32) NOT NULL, 
direccion VARCHAR(100) NOT NULL, 
bonificacion INT NOT NULL, 
sueldo INT NOT NULL, PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


CREATE TABLE Cliente (
id INT AUTO_INCREMENT NOT NULL, 
nombre VARCHAR(64) NOT NULL, 
apellido VARCHAR(64) NOT NULL, 
telefono VARCHAR(32) NOT NULL, 
direccion VARCHAR(100) NOT NULL, 
afiliado VARCHAR(2) NOT NULL, 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;



CREATE TABLE Inventario (
id INT AUTO_INCREMENT NOT NULL, 
idproducto INT DEFAULT NULL, 
cantidad VARCHAR(64) NOT NULL, 
INDEX IDX_25444D25D6E4E18 (idproducto), 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;



CREATE TABLE Producto (
id INT AUTO_INCREMENT NOT NULL, 
idproveedor INT DEFAULT NULL, 
nombre VARCHAR(64) NOT NULL, 
precio VARCHAR(100) NOT NULL, 
iva VARCHAR(100) NOT NULL, 
INDEX IDX_5ECD644368DBC13B (idproveedor), 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;



CREATE TABLE Proveedor (
id INT AUTO_INCREMENT NOT NULL, 
nombre VARCHAR(64) NOT NULL, 
apellido VARCHAR(64) NOT NULL, 
telefono VARCHAR(32) NOT NULL, 
direccion VARCHAR(100) NOT NULL, 
garantia INT NOT NULL, 
tiempoEntrega INT NOT NULL, 
precio INT NOT NULL, PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;




CREATE TABLE Transaccion (
id INT AUTO_INCREMENT NOT NULL, 
descripcion VARCHAR(64) NOT NULL, 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE Movimiento (
id INT AUTO_INCREMENT NOT NULL, 
idcliente INT DEFAULT NULL, 
idusuario INT DEFAULT NULL, 
idproducto INT DEFAULT NULL, 
idtransaccion INT DEFAULT NULL, 
garantia INT NOT NULL, 
INDEX IDX_87A213AA2B18C94B (idcliente), 
INDEX IDX_87A213AAFD61E233 (idusuario), 
INDEX IDX_87A213AAD6E4E18 (idproducto), 
INDEX IDX_87A213AA79381A58 (idtransaccion), 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


ALTER TABLE Movimiento ADD CONSTRAINT FK_87A213AA2B18C94B FOREIGN KEY (idcliente) REFERENCES Cliente (id);
ALTER TABLE Movimiento ADD CONSTRAINT FK_87A213AAFD61E233 FOREIGN KEY (idusuario) REFERENCES Usuario (id);
ALTER TABLE Movimiento ADD CONSTRAINT FK_87A213AAD6E4E18 FOREIGN KEY (idproducto) REFERENCES Producto (id);
ALTER TABLE Movimiento ADD CONSTRAINT FK_87A213AA79381A58 FOREIGN KEY (idtransaccion) REFERENCES Transaccion (id);
ALTER TABLE Inventario ADD CONSTRAINT FK_25444D25D6E4E18 FOREIGN KEY (idproducto) REFERENCES Producto (id);
ALTER TABLE Producto ADD CONSTRAINT FK_5ECD644368DBC13B FOREIGN KEY (idproveedor) REFERENCES Proveedor (id);