app_cliente:
    resource: "@appBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

app_proveedor:
    resource: "@appBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor

app_transaccion:
    resource: "@appBundle/Resources/config/routing/transaccion.yml"
    prefix:   /transaccion

app_homepage:
    path:     /hello/{name}
    defaults: { _controller: appBundle:Default:index }
