inventario:
    path:     /
    defaults: { _controller: "appBundle:Inventario:index" }

inventario_show:
    path:     /{id}/show
    defaults: { _controller: "appBundle:Inventario:show" }

inventario_new:
    path:     /new
    defaults: { _controller: "appBundle:Inventario:new" }

inventario_create:
    path:     /create
    defaults: { _controller: "appBundle:Inventario:create" }
    requirements: { _method: post }

inventario_edit:
    path:     /{id}/edit
    defaults: { _controller: "appBundle:Inventario:edit" }

inventario_update:
    path:     /{id}/update
    defaults: { _controller: "appBundle:Inventario:update" }
    requirements: { _method: post|put }

inventario_delete:
    path:     /{id}/delete
    defaults: { _controller: "appBundle:Inventario:delete" }
    requirements: { _method: post|delete }
